services:
  dbt-yelp:
    build:
      context: .
      dockerfile: Dockerfile
    image: hut-ch/dbt-yelp:dev
    volumes:
      - ./:/yelp-reviews:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres-yelp
    hostname: pg-yelp
    restart: unless-stopped
    volumes:
      - .db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yelp
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yelp"]
      interval: 10s
      timeout: 30s
      retries: 5

  pgadmin:
    container_name: pgadmin-yelp
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=yelp@reviews.com
      - PGADMIN_DEFAULT_PASSWORD=yelp
    ports:
      - '8080:80'
    #volumes:
    #  - ./config/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
