services:
  dbt-yelp:
    build:
      context: .
      dockerfile: Dockerfile
    image: hut-ch/dbt-yelp:dev
    volumes:
      - ./:/yelp-reviews:cached
      - .dbt:/root/.dbt:cached
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    hostname: pg-yelp
    restart: unless-stopped
    volumes:
      - .db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yelp
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yelp"]
      interval: 10s
      timeout: 30s
      retries: 5
